pipeline {
    agent any

    stages{
        stage ('Clean workspace') {
            steps {
                echo 'Cleaning workspace.'
                cleanWs()
            }
        }
        stage ('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/eryxjose/Personactivities.git'
            }
        }
        stage('Restore packages') {
            steps {
                bat "dotnet restore ${workspace}\\personactivities\\Personactivities.sln"
            }
        }
        stage('Increase version') {
            steps {
                echo "${env.BUILD_NUMBER}"
                
            }
        }
        stage('Build') {
            steps {
                bat "msbuild.exe ${workspace}\\personactivities\\personactivities.sln /nologo /nr:false  /p:platform=\"x64\" /p:configuration=\"release\" /p:PackageCertificateKeyFile=<path-to-certificate-file>.pfx /t:clean;restore;rebuild"
            }
        }
    }
}
