pipeline {
    agent any

    stages{
        stage ('Clean workspace') {
            steps {
                echo 'Cleaning workspace.'
                cleanWs()
            }
        }
        stage('Build') {
            steps {
                sh "docker-compose -f docker-compose.yml up --build -d"
            }
        }
    }
}
