pipeline {
    agent any

    stages{
        stage ('Clean workspace') {
            steps {
                echo 'Cleaning workspace.'
                cleanWs()
            }
        }
        stage('Example') {
            steps {
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
            }
        }
        stage('Build') {
            steps {
                sh "docker --help"
            }
        }
    }
}
